### ISSUE TITLE
Tests fail on nightly/beta 1.66+

### ISSUE THREAD

**Issue by tonowak** [obi1kenobi/cargo-semver-checks#175]
### Steps to reproduce the bug with the above code

Run `cargo test` using `cargo 1.67.0-nightly (9286a1beb 2022-11-04)`

### Actual Behaviour

```
failures:

---- query::tests::derive_trait_impl_removed stdout ----
thread 'query::tests::derive_trait_impl_removed' panicked at 'assertion failed: `(left == right)`
  left: `[{"name": String("DebugFoo"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("DebugFoo")]), "span_begin_line": Uint64(7), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("Debug"), "trait_path": List([String("core"), String("fmt"), String("Debug")]), "visibility_limit": String("public")}, {"name": String("CopyBar"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("CopyBar")]), "span_begin_line": Uint64(17), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("Copy"), "trait_path": List([String("core"), String("marker"), String("Copy")]), "visibility_limit": String("public")}, {"name": String("EqFoo"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("EqFoo")]), "span_begin_line": Uint64(27), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("Eq"), "trait_path": List([String("core"), String("cmp"), String("Eq")]), "visibility_limit": String("public")}]`,
 right: `[{"name": String("DebugFoo"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("DebugFoo")]), "span_begin_line": Uint64(7), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("Debug"), "trait_path": List([String("core"), String("fmt"), String("Debug")]), "visibility_limit": String("public")}, {"name": String("CopyBar"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("CopyBar")]), "span_begin_line": Uint64(17), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("Copy"), "trait_path": List([String("core"), String("marker"), String("Copy")]), "visibility_limit": String("public")}, {"name": String("EqFoo"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("EqFoo")]), "span_begin_line": Uint64(27), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("StructuralEq"), "trait_path": List([String("core"), String("marker"), String("StructuralEq")]), "visibility_limit": String("public")}, {"name": String("EqFoo"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("EqFoo")]), "span_begin_line": Uint64(27), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("Eq"), "trait_path": List([String("core"), String("cmp"), String("Eq")]), "visibility_limit": String("public")}, {"name": String("ManualEqFoo"), "path": List([String("semver_tests"), String("test_cases"), String("derive_trait_impl_removed"), String("ManualEqFoo")]), "span_begin_line": Uint64(38), "span_filename": String("src/test_cases/derive_trait_impl_removed.rs"), "trait_name": String("StructuralEq"), "trait_path": List([String("core"), String("marker"), String("StructuralEq")]), "visibility_limit": String("public")}]`', src/query.rs:260:9
```

### Expected Behaviour

I expect the tests to pass.

#### Software version

cargo-semver-checks 0.12.1

#### Operating system

Linux 6.0.6-arch1-1

#### Command-line

```bash
/home/tonowak/.cargo/bin/cargo-semver-checks semver-checks --bugreport
```

#### cargo nightly version

```
> cargo +nightly -V
cargo 1.67.0-nightly (9286a1beb 2022-11-04)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,llvm14-builtins-abi,sse,sse2
- Host: x86_64-unknown-linux-gnu

### Additional Context

This appears to be due to a new marker trait StructuralEq added in 1.66+.

**Comment by obi1kenobi** [comment]
A few different options to fix this:
- Explicitly filter out `StructuralEq` from the derived traits lint rule, since it's a "rustc internal use only" unstable trait, so not really user-facing.
- Have different test files specifying different expected test outputs on different rustc versions, so that 1.65 can continue to not return `StructuralEq` while 1.66+ requires `StructuralEq` to be found.

There are pros and cons to both. Are there any alternatives I'm missing?

**Comment by tonowak** [comment]
The second options sounds better for the future (the easiest probably would be passing multiple outputs and accepting the test when at least one output would match). What pros do you see in the first solution?

**Comment by obi1kenobi** [comment]
The pros of the first solution is that we can do it in 30 seconds and move on to something else :) In an ideal world with unlimited time and resources, we'd do everything perfectly, but that's never the case in practice. From our users' point of view, they wouldn't be able to tell the difference between the two approaches, so I feel like we should probably do the faster one for now and then invest our limited time and energy into something more impactful. If we need to reverse this decision in the future, that's easy too -- just remove the extra filter.

If going with the second option, I don't think we want to pass multiple outputs and accept if any of them match. I think we'd want a to match against a single concrete expected output. Consider this buggy implementation: with 50% probability, output one possible output, and with 50% probability output the other. `cargo-semver-checks` queries should be deterministic on any given codebase and Rust version, but this implementation would not be detected or prevented by this test approach.

**Comment by tonowak** [comment]
I think it is reasonable to do the easiest solution and later consider improving it when in the future there'll be a similar situation.

**Comment by tonowak** [comment]
It seems this issue is no longer present?
I'm using `cargo +nightly  test` on `cargo 1.67.0-nightly (9286a1beb 2022-11-04)`

**Comment by tonowak** [comment]
Ok, I don't know what's going on. I'm using the exact same version of `cargo` as when the test failed.

**Comment by tonowak** [comment]
Nevermind, I forgot to run `scripts/regenerate_test_rustdocs.sh`. The test still fails.

And by the way, I find it weird that this command is not run automatically on `cargo test`. Is there a reason? Sometimes I forget to run it, just like now...

**Comment by obi1kenobi** [comment]
> And by the way, I find it weird that this command is not run automatically on `cargo test`. Is there a reason? Sometimes I forget to run it, just like now...

The script takes a little while to run, so it would slow down our iteration speed if it re-ran on every `cargo test`. I never figured out a good way to get it to only run when it's actually needed (test case changes + changes in Rust version only), but I also didn't look particularly hard.

If you'd like to look into a way to get it to run automatically and only as necessary, please do! I also sometimes forget to run it, and I'd be thrilled to not have to remember to do it by hand.

**Comment by tonowak** [comment]
Maybe by appending a hash of the test and the used cargo version to the end of the filename, and when that filename doesn't exist, run rustdoc and save the output to this file? That won't detect changes in the trustfall and the adapter, though.

**Comment by obi1kenobi** [comment]
Yeah, it's tricky with lots of edge cases. And a complex system that only covers part of the situations is worse than no system at all: instead of remembering to run the script, we'd have to remember when running the script is something the system will do vs when do we have to do it manually + then actually remember to run it.

**Comment by tonowak** [comment]
Maybe it would be better to somehow add a flag to `cargo test` that disables generating the rustdocs? Then, by default, it would generate the docs (which isn't bad) and when we would like it to be faster (during the development of the project), looking at the ran command would kind of remind that it doesn't regenerate the docs and that regenerating the docs might change the output. In short, I think that generating the docs should be the default option and speeding this process by not generating them should be an explicit option.

**Comment by obi1kenobi** [comment]
Keep in mind that every new mode of operation that's added to a tool (like a flag for changing whether something happens or not) means more things that need to be understood, documented, tested, kept in mind, and continue to work correctly. So this isn't just a matter of adding some code — in fact the code is the easiest part of all here.

If despite that warning you still feel strongly about this existing, by all means go ahead and prototype it.

**Comment by tonowak** [comment]
Putting aside this specific solution and its consequences, I'm more interested in why currently it is like that. From my understanding, this script is only for contributors to speed up the process of testing. Going with your argument, this script is also something that needs to be understood and kept in mind (and as you can see from my comments above, I forgot to keep it in mind, thus I'm complaining about the existence of the script). Instead of the script being the default option, it seems to be safer to just run it at the beginning of `cargo test`, unless the user wants the tests to run fast. In this case, I don't have to keep anything in mind, but if I wanted it to be faster, I could somehow explicitly tell the tool to skip the tests. I agree that such an option would be one more thing to check whether it works correctly, but if one day it would stop working and nobody would realize it, maybe the script was not needed after all. What do you think about this approach? (I'm not yet trying to convince you to do it like that -- I'm only wondering which solution is better)

**Comment by obi1kenobi** [comment]
No worries at all. This is kind of design analysis and decision-making is the real subject of software engineering — the rest is just typing 😄

It's clear that neither approach is perfect. Both approaches have downsides, and we have to pick the least-bad option.

A few cornerstones:
- No matter what, GitHub Actions CI always regenerates the rustdoc JSON files by running the script. We never want to merge incorrect code and this is what guarantees that safety property.
- Being able to test locally is an optimization on that process: instead of waiting for a GitHub Actions CI run, we run the test suite ourselves. This is a process we expect to run many times, so it's important that it's very fast *by default*.
- We're assuming that most of the work on `cargo-semver-checks` is done by a relatively small number of frequent contributors + occasional new contributors who receive mentorship and advice from the existing contributors. This is the case for most open-source projects, and `cargo-semver-checks` is no exception.

In a hypothetical scenario, it would even be worth accepting a small fraction of a percent of false negative (tests failed to find a bug) or false positive (tests failed but there's no bug) outcomes if that tradeoff gives us e.g. a 10x speedup otherwise. This is because safety is guaranteed by **CI** and not by our local `cargo test`. For example, consider the following test setup:
- If all tests in `cargo test` passed locally, assume the result is a true negative (no bug). This is safe because CI will verify it, and a small fraction of the time it will reveal our local result as a false negative (there was a bug).
- If some test in `cargo test` failed locally, assume the result is a false positive (no bug): regenerate the rustdoc JSON, then re-run `cargo test`. This second `cargo test` run should have no false outcomes, and should clearly show whether there was a bug or not.

In this scenario, say that `cargo test` by itself costs 1 unit of time, and regenerating rustdoc JSON costs 9 units (so regenerate + run `cargo test` is 10 units, i.e. not-regenerating is a 10x speedup: 10 units -> 1 unit).

If regenerating rustdoc every time, both test successes and test failures cost 10 units each.

If using the test setup I described above, when `cargo test` passes locally that takes 1 unit of time and when `cargo test` fails locally, that's now 11 units of time (two `cargo test` runs + regenerating the rustdoc JSON).

With a bit of math (let `x` be the test success fraction, solve `x + (1 - x) * 11 = 10`), we see that so long as no more than 90% of all our `cargo test` runs fail locally, it's advantageous to adopt the "only regenerate on test failure" test setup I described.

A few observations about how this thought experiment relates to reality:
- Not regenerating rustdoc JSON is easily at least a 10x improvement; it's likely much more. Furthermore, the difference is likely to grow over time, since generating rustdoc JSON is much slower than querying it in our test cases. This means in practice that the 90% test failure figure would need to be even higher before this stops being worth it.
- We can further improve this test procedure: instead of always regenerating rustdoc JSON on failed tests, we could only regenerate if a new test case was added or if the Rust version was changed — which are not the common case. So that 90% figure would need to be even higher still.
- A 90% test failure rate is already rather high! Try recording the outcomes of your local `cargo test` runs and you'll see they generally don't fail 9-in-10 times, let alone significantly more than that.

I'm not suggesting that we *write code* to implement this test procedure automatically. But it is a viable test procedure we could adopt manually with the existing primitives we already have at our disposal. It's the best interpretation of the status quo.

The alternative approach is to opt out of regenerating rustdoc JSON via a flag — but the common case is one where we don't need to regenerate. And yet our UX choice has resulted in not just more technical complexity but also more work in the common case: we need to add the flag *most of the time*. If the default suggestion is to override a default value, that's a sign of a bad default value. The biggest beneficiary of this alternative approach would be new contributors that don't know about the script for regenerating rustdoc JSON files, but per our assumptions such folks would be receiving mentorship from existing contributors and in general such new contributors coming to the project are relatively rare compared to the pace of work of the project itself.

Obviously, at the end of the day this comes down to a judgment call: are our starting assumptions reasonable, will they change in the future and how soon, what the relative intensity of the upsides and downsides is, etc. In my judgment call, the flag to skip generating rustdocs has downsides that outweigh the benefits, so we'd be better off sticking with the status quo.

**Comment by tonowak** [comment]
Thanks for the detailed answer! I now understand the decision.
One question, though - 1:9 proportions of execution seems to be much bigger than in reality, I've experienced more like 1:1 or 1:2. Is it indeed so slow locally for you?
Also, what do you think about running the rustdocs in parallel? Then the execution time would be much faster than `cargo test` and it could be ran each time.

**Comment by obi1kenobi** [comment]
I'm not sure how much benefit there might be in running rustdoc generation in parallel, since rustc does attempt to parallelize to all available cores. If not done very carefully, that could introduce a net slowdown as different rustc invocations assume they independently have access to all cores and proceed to step all over each other.

I just measured the difference again and the ratio is currently 1:2.5 on my machine: ~6s to run tests vs ~15s to regenerate rustdoc. It went down when I added the four test cases that check renamed targets, since those test cases always regenerate their own rustdoc and that's quite slow.

It's also important to consider how this ratio might change over time: we're likely to have more rustdoc to regenerate via the script as we add more checks, and future rustdoc is likely going to be more complex as we add more sophisticated lints. That means that both the ratio and the overall test time are likely to grow in the future, meaning it's even more valuable to try to keep the test time short in order for our iteration speed to be fast.
