### ISSUE TITLE
Running `cargo semver-checks` with no other arguments should default to checking

### ISSUE THREAD

**Issue by Lokathor** [obi1kenobi/cargo-semver-checks#414]
### Describe your use case

I ran `cargo semver-checks` and it said i needed to pick a command or argument.

### Describe the solution you'd like

Instead it should "do the right thing" and just do the checks if no command or argument is provided.

**Comment by obi1kenobi** [comment]
100% agreed. Originally, I thought we might have multiple subcommands, but that turned out to not be the case and I've even considered deprecating `check-release` as a subcommand instead of just running it by default. I'm still not sure if we should go *that* far, but certainly running `check-release` by default would be an improvement.

If you'd be open to putting together a PR for this, I'd be thrilled to merge it.

**Comment by obi1kenobi** [comment]
Related to: https://github.com/obi1kenobi/cargo-semver-checks/issues/86#issuecomment-1374672344

**Comment by era** [comment]
@obi1kenobi I can send a PR changing the behaviour to run check-release by default.

**Comment by obi1kenobi** [comment]
Sounds great, thank you!

**Comment by obi1kenobi** [comment]
Fixed in #459 and shipped already, just forgot to close this issue!
