### ISSUE TITLE
Consider switching to `anstyle` for our terminal styling and color needs

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#724]
> Tangential comment. Please disregard since it's only for future note.*
> 
> The recommended SOTA color-related logic is to use the [rust-cli/anstyle](https://github.com/rust-cli/anstyle) crates.*

_Originally posted by @pksunkara in https://github.com/obi1kenobi/cargo-semver-checks/issues/721#issuecomment-2027124448_

It seems that multiple of our dependencies already use `anstyle`, so we should consider switching to it as well.

**Comment by pksunkara** [comment]
I can mentor on this issue.

**Comment by suaviloquence** [comment]
Hi! Thanks for the offer to help!  Would common practice be to use the `anstyle-termcolor` crate or refactor entirely to use the `anstream` crate?

**Comment by pksunkara** [comment]
I might be wrong but I consider `anstyle-termcolor` to be more related to style customization logic.

The color logic we need to clean up here is more about the setup including respecting user's preferences. I have a sample boilerplate for CLIs that sets up everything related to color at https://git.sr.ht/~pksunkara/cli-clap.

There are quite a few important parts such as:

* Reading `--color` argument, https://git.sr.ht/~pksunkara/cli-clap/tree/master/item/src/main.rs#L38
* Forwarding color choice to logging, https://git.sr.ht/~pksunkara/cli-clap/tree/master/item/src/main.rs#L45
* Outputting text while respecting color choice, https://git.sr.ht/~pksunkara/cli-clap/tree/master/item/src/hello.rs#L24

**Comment by pksunkara** [comment]
To answer the original question,

Since we must respect the color choices set in various ways (as described in `anstyle-query`), we must bring in `anstream`.  And then have a generic output function that uses `anstyle-termcolor` to convert the `termcolor` usage to `anstyle` before printing. This is the way people would choose to migrate if they have a lot of places where they need to migrate.

But since, we have only a few places and also use `termcolor_output` to currently print that we can't easily modify, and we are bringing in `anstream` anyway, I would recommend the refactor to `anstream` crate completely.

**Comment by suaviloquence** [comment]
just a thought while I work on this - does it make sense to also refactor to use something like the `log` crate for managing log levels?

**Comment by pksunkara** [comment]
If you want to do that, I would recommend `tracing` instead ([setup](https://git.sr.ht/~pksunkara/cli-clap/tree/master/item/src/main.rs#L40) and [usage](https://git.sr.ht/~pksunkara/cli-clap/tree/master/item/src/hello.rs#L26))

**Comment by suaviloquence** [comment]
Closed in #737

**Comment by obi1kenobi** [comment]
Implemented in #737.
